// AUTOGENERATED FILE
// This file was generated from formula.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface FormulaActionDict<T> extends BaseActionDict<T> {
  Expression?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AddStatement_plus?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AddStatement_minus?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AddStatement?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  MultiStatement_times?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  MultiStatement_divide?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  MultiStatement?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PriorityStatement_paren?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  PriorityStatement?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  number_fract?: (this: NonterminalNode, arg0: IterationNode, arg1: TerminalNode, arg2: IterationNode) => T;
  number_whole?: (this: NonterminalNode, arg0: IterationNode) => T;
  number?: (this: NonterminalNode, arg0: NonterminalNode) => T;
}

export interface FormulaSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: FormulaActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: FormulaActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: FormulaActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: FormulaActionDict<T>): this;
}

export interface FormulaGrammar extends Grammar {
  createSemantics(): FormulaSemantics;
  extendSemantics(superSemantics: FormulaSemantics): FormulaSemantics;
}

declare const grammar: FormulaGrammar;
export default grammar;

